spring.application.name=personas-api


spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=personas_api;encrypt=true;trustServerCertificate=true
spring.datasource.username=personas_user
spring.datasource.password=TuPasswordFuerte123!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
